name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Kör när det sker en push till main
  workflow_dispatch:  # Gör det möjligt att köra manuellt

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Bygg projektet, vilket skapar dist/ mappen

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages  # Deployment till gh-pages branchen
          publish_dir: ./dist  # Sätt till den mapp där dina byggda filer ligger (dist)
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Autentisering via GitHub token
